export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CHANGE_ITEM_COUNT = 'CHANGE_ITEM_COUNT';
export const CALCULATE_AMOUNT = 'CALCULATE_AMOUNT';
